### ISSUE TITLE
questions about detect the Nm of mRNA by NanoNm

### ISSUE THREAD

**Issue by mlpy18** [YanqiangLi/NanoNm#1]
hello there, we tried to use the NanoNm to detect the Nm site of directRNA-seq data, but we could not get the results, some steps of the pipeline doesn't work. So, we would like to know what kind of files or data should we prepared beside directRNA-seq data before we start analysis. Can you provide some details instructions about this tool, which will help us a lot. Thank you.

**Comment by YanqiangLi** [comment]
Thanks for your question, I updated the readme file, it is applied to human genome. Hope it helps. 

#downloaded gencode.v27.transcripts.fa  from https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_27/gencode.v27.transcripts.fa.gz

multi_to_single_fast5  -i ${id}.fast5 -s $id  --recursive -t 40

guppy_basecaller --input_path $id --save_path $id_guppy --num_callers 40 --recursive --fast5_out --config rna_r9.4.1_70bps_hac.cfg  --cpu_threads_per_caller 10

tombo resquiggle --rna --overwrite  ${id}\_guppy/workspace/  gencode.v27.transcripts.fa    --processes 40 --fit-global-scale --include-event-stdev 


python extract_raw_and_feature_fast_AUCG.py  --cpu=30 --fl = ${id}_guppy.list -o ${id}_guppy.feature --clip=5

cat *.feature.feature.fa >all.feature.fa

cat *.feature.feature.tsv >all.feature.tsv 

python predict_sites_Nm.final.py   --model ./model --cpu 20  -i all -o all_Nm_model -r  gencode.v27.transcripts.fa  -g GRCh38.p13.genome.fa  -b hg38.gene2transcripts.txt

**Comment by mlpy18** [comment]
Thank you for your quick reply, we will try again.

**Comment by mlpy18** [comment]
Hello Dr. Li,
we tired to run the pipeline again, however, there still are some questions. First, how can we get/produce the 'rRNA.Nm1.bed' file in step 1.6 and the 'hg38.gene2transcripts.txt' file in step 3; Second, Do we need to run the whole pipeline from step 1 to step 3, or just run the step3 if we want to detect the Nm of mRNA sequencing data.
Thank you

**Comment by YanqiangLi** [comment]
Yes. You do not need to run step 1-2. You can just use the model to predict Nm in your data from step3.
Best,
Yanqiang

From: mlpy18 ***@***.***>
Date: Tuesday, August 13, 2024 at 04:54
To: YanqiangLi/NanoNm ***@***.***>
Cc: Yanqiang Li ***@***.***>, State change ***@***.***>
Subject: Re: [YanqiangLi/NanoNm] questions about detect the Nm of mRNA by NanoNm (Issue #1)

Hello Dr. Li,
we tired to run the pipeline again, however, there still are some questions. First, how can we get/produce the 'rRNA.Nm1.bed' file in step 1.6 and the 'hg38.gene2transcripts.txt' file in step 3; Second, Do we need to run the whole pipeline from step 1 to step 3, or just run the step3 if we want to detect the Nm of mRNA sequencing data.
Thank you

**Comment by mlpy18** [comment]
Thank you for your kind reply. However, we still encounter a problem, it seems there are something wrong about the 'hg38.gene2transcripts.txt' file, how to prepare the right 'hg38.gene2transcripts.txt' file.
![微信图片_20240814165035](https://github.com/user-attachments/assets/0aebdce4-cf4f-4722-9f5e-a85d8c456792)
![微信图片_20240814165035](https://github.com/user-attachments/assets/80d2193b-c146-4163-bd41-e728250eb7ac)

**Comment by YanqiangLi** [comment]
The hg38.gene2transcripts.txt is prepared already. Could you please check the transcript.fa file . The format may like this:
***@***.***

You can change the first “|” to tab.

Best,
Yanqiang
From: mlpy18 ***@***.***>
Date: Wednesday, August 14, 2024 at 04:52
To: YanqiangLi/NanoNm ***@***.***>
Cc: Yanqiang Li ***@***.***>, State change ***@***.***>
Subject: Re: [YanqiangLi/NanoNm] questions about detect the Nm of mRNA by NanoNm (Issue #1)

Thank you for your kind reply. However, we still encounter a problem, it seems there are something wrong about the 'hg38.gene2transcripts.txt' file, how to prepare the right 'hg38.gene2transcripts.txt' file.
_20240814165035.png (view on web)<https://github.com/user-attachments/assets/0aebdce4-cf4f-4722-9f5e-a85d8c456792>
_20240814165035.png (view on web)<https://github.com/user-attachments/assets/80d2193b-c146-4163-bd41-e728250eb7ac>

**Comment by mlpy18** [comment]
Thank you for your help, we have change the first “|” to tab of the file, but we encounter a new problem.
![FA](https://github.com/user-attachments/assets/c7c30781-320e-4607-9aee-c71d574f0ca2)
![BUG](https://github.com/user-attachments/assets/99883a1c-8585-4b9c-b42f-d0f43494979a)

**Comment by YanqiangLi** [comment]
Please use this:

  $samtools faidx  GRCh38.p13.genome.fa

  $picard CreateSequenceDictionary R=GRCh38.p13.genome.fa O=GRCh38.p13.genome.dict

From: mlpy18 ***@***.***>
Date: Wednesday, August 14, 2024 at 22:36
To: YanqiangLi/NanoNm ***@***.***>
Cc: Yanqiang Li ***@***.***>, State change ***@***.***>
Subject: Re: [YanqiangLi/NanoNm] questions about detect the Nm of mRNA by NanoNm (Issue #1)

Thank you for your help, we have change the first “|” to tab of the file, but we encounter a new problem.
FA.png (view on web)<https://github.com/user-attachments/assets/c7c30781-320e-4607-9aee-c71d574f0ca2>
BUG.png (view on web)<https://github.com/user-attachments/assets/99883a1c-8585-4b9c-b42f-d0f43494979a>

**Comment by mlpy18** [comment]
Thank you very much, but there is another problem.
![model](https://github.com/user-attachments/assets/600c3e42-1cab-4e28-9a22-57301c78ad85)

**Comment by YanqiangLi** [comment]
Thanks for pointing this out.
The script was updated. In the 466th line, it should be:
                for tpp in ["AAATC","AAATG","AAGAG","AATAC","AATGT","ACACG","ACAGC","ACTCT","AGAGA","AGAGC","AGATT","AGCAA","AGCAG","AGCCA","AGCGT","AGGGA","AGGGC","AGGGG","AGGTT","AGTAC","ATATG","ATCCA","ATCTT","ATGGA","ATGTG","ATTCC    ","ATTGT","CAAAG","CACTA","CAGAC","CAGGT","CAGTT","CCATA","CCCAG","CCGAA","CCGGT","CCGTC","CGCCC","CGCTG","CGTTT","CTCCA","CTCTG","CTTCT","CTTGA","CTTGC","GAAAG","GAACG","GAACT","GAAGA","GACCG","GACGA","GACGC","GAGGG","GAGGT",    "GATTG","GCAAA","GCAGA","GCCAA","GCCCG","GCCGG","GGAAG","GGAGA","GGATC","GGCAT","GGCGG","GGCTC","GGGGA","GGGGC","GGGTA","GGTAA","GGTGG","GGTGT","GTAGC","GTAGT","GTCCC","GTCTA","GTGTC","GTTCA","GTTCC","TAACT","TAATC","TAATT","T    ACAT","TAGAG","TAGCA","TAGCG","TCATT","TCGGG","TCGTC","TGAGC","TGATG","TGGGG","TGGTG","TGTGA","TTAAA","TTAAG","TTGCA","TTGGA","TTGTT","TTTGG"]

From: mlpy18 ***@***.***>
Date: Thursday, August 15, 2024 at 22:42
To: YanqiangLi/NanoNm ***@***.***>
Cc: Yanqiang Li ***@***.***>, State change ***@***.***>
Subject: Re: [YanqiangLi/NanoNm] questions about detect the Nm of mRNA by NanoNm (Issue #1)

Thank you very much, but there is another problem.
model.png (view on web)<https://github.com/user-attachments/assets/600c3e42-1cab-4e28-9a22-57301c78ad85>

**Comment by mlpy18** [comment]
Thank you for your help, we completed the analysis, and there are lots of results in the "all_Nm_model" folder. we would like to know which are the key results, and is there a description of this results, such as the 'ratio.0.5.tsv' .
![image](https://github.com/user-attachments/assets/81633455-6a13-4c06-917e-14c2eed22e24)
![image](https://github.com/user-attachments/assets/4ddd64e8-6038-4576-9270-c87858f5d7ec)

**Comment by YanqiangLi** [comment]
You are right!  The key result is ratio.0.5.tsv. You can transform it into a bed file with this custom python script https://github.com/YanqiangLi/NanoNm/blob/main/filter0.5.bed.ratio.py  with python2.7  ~/liyq/bin/filter0.5.bed.ratio.py  ratio.0.5.tsv  filter
The ratio.0.5.tsv include gene name, chromosome information, position in the chromosome, methylated reads, total reads and methylation ratio.

From: mlpy18 ***@***.***>
Date: Monday, August 19, 2024 at 04:29
To: YanqiangLi/NanoNm ***@***.***>
Cc: Yanqiang Li ***@***.***>, State change ***@***.***>
Subject: Re: [YanqiangLi/NanoNm] questions about detect the Nm of mRNA by NanoNm (Issue #1)

Thank you for your help, we completed the analysis, and there are lots of results in the "all_Nm_model" folder. we would like to know which are the key results, and is there a description of this results, such as the 'ratio.0.5.tsv' .
image.png (view on web)<https://github.com/user-attachments/assets/81633455-6a13-4c06-917e-14c2eed22e24>
image.png (view on web)<https://github.com/user-attachments/assets/4ddd64e8-6038-4576-9270-c87858f5d7ec>
